# Generated by Django 2.2.5 on 2022-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
