# Generated by Django 2.2.5 on 2022-08-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='rent.Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='rent.Customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(auto_now=True),
        ),
    ]
