# Generated by Django 4.1 on 2022-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
