# Generated by Django 4.1.4 on 2022-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JOGGING', 'Jogging'), ('SWIMMING', 'Swimming'), ('BIKING', 'Biking'), ('YOGA', 'Yoga'), ('WEIGHTLIFTING', 'Weightlifting')], help_text='Enter workout type', max_length=20)),
                ('duration', models.IntegerField(help_text='Enter workout duration (minutes)', max_length=3)),
            ],
            options={
                'ordering': ['-type'],
            },
        ),
    ]
