# Generated by Django 4.1.4 on 2023-01-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('JOGGING', 'Jogging'), ('SWIMMING', 'Swimming'), ('BIKING', 'Biking'), ('YOGA', 'Yoga'), ('PUSHUPS', 'Pushups'), ('SITUPS', 'Situps')], help_text='Enter workout type', max_length=20),
        ),
    ]
