# Generated by Django 4.1.4 on 2023-01-03 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_options_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 14, 4, 40, 332104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(help_text='Enter workout duration (minutes)'),
        ),
    ]
