# Generated by Django 4.1.3 on 2023-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workout_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=0, help_text='(minutes or repos depending on workout type)'),
        ),
    ]
