# Generated by Django 4.1.3 on 2023-01-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workout_duration'),
        ('workouts', '0007_workout_user_alter_workout_duration'),
    ]

    operations = [
    ]
